/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_starcor_xul_XulUtils */

#ifndef _Included_com_starcor_xul_XulUtils
#define _Included_com_starcor_xul_XulUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_starcor_xul_XulUtils
 * Method:    _native_do_blur
 * Signature: (Ljava/nio/Buffer;III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_starcor_xul_XulUtils__1native_1do_1blur
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     com_starcor_xul_XulUtils
 * Method:    _native_do_fast_blur
 * Signature: (Ljava/nio/Buffer;III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_starcor_xul_XulUtils__1native_1do_1fast_1blur
  (JNIEnv *, jclass, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
