/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kingz_jni_BitmapTools */

#ifndef _Included_com_kingz_jni_BitmapTools
#define _Included_com_kingz_jni_BitmapTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kingz_jni_BitmapTools
 * Method:    dobulr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kingz_jni_BitmapTools_dobulr
  (JNIEnv *, jclass)
{
    return  (*env)->NewStringUTF(env,"hello 52pojie!");
}

#ifdef __cplusplus
}
#endif
#endif
