@startuml
package "UI组件" {
    ["SeekBar"]
    ["组件1.2"]
    ["组件2.1"]
}

node "播控组件" {
    ["组件2.1"] - ["UI模块"]
    ["数据储存"] - [播放数据储存]

    ["UI模块"] --> ["数据储存"]
}

cloud "播放数据储存"{
    [数据储存] -> [逻辑服务器1]
    [数据储存] -> [逻辑服务器2]
    [数据储存] -> [逻辑服务器3]
}

database "MySql" {
    folder "This is my folder" {
        [Folder 3]
    }

    frame "Foo" {
        [Frame 4]
    }
}

[逻辑服务器1] --> [Folder 3]
[逻辑服务器2] --> [Frame 4]
[逻辑服务器3] --> [Frame 4]
@enduml